[package]
name = "minecraft_server_status_bot"
version = "0.5.0"
authors = ["Jakub Tomana <jakub.tomana@protonmail.com>"]
edition = "2018"

[dependencies]
serenity = "0.5"
reqwest = "0.9.8"
serde_json = "1.0"